//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadnik.MAUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roadnik.MAUI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generic_ago {
            get {
                return ResourceManager.GetString("generic.ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generic_cancel {
            get {
                return ResourceManager.GetString("generic.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generic_hours {
            get {
                return ResourceManager.GetString("generic.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generic_minutes {
            get {
                return ResourceManager.GetString("generic.minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generic_seconds {
            get {
                return ResourceManager.GetString("generic.seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success: %success%/%total% (last: %last-successful-report%)
        ///Last location fix: %last-location-fix% (%last-location-fix-accuracy%m) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_body {
            get {
                return ResourceManager.GetString("notification.location_sharing.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   never に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_body_never {
            get {
                return ResourceManager.GetString("notification.location_sharing.body_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your location is being shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_title {
            get {
                return ResourceManager.GetString("notification.location_sharing.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %body に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_push_new_point_body {
            get {
                return ResourceManager.GetString("notification.push.new_point.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User &apos;%username&apos; has added new point to map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_push_new_point_title {
            get {
                return ResourceManager.GetString("notification.push.new_point.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to open map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_push_new_track_body {
            get {
                return ResourceManager.GetString("notification.push.new_track.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User &apos;%username&apos; has started a new track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_push_new_track_title {
            get {
                return ResourceManager.GetString("notification.push.new_track.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_about_updateAvailable {
            get {
                return ResourceManager.GetString("page.about.updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_about_updating {
            get {
                return ResourceManager.GetString("page.about.updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_delete {
            get {
                return ResourceManager.GetString("page.bookmarks.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pull left to delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_delete_hint {
            get {
                return ResourceManager.GetString("page.bookmarks.delete_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_room {
            get {
                return ResourceManager.GetString("page.bookmarks.room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_username {
            get {
                return ResourceManager.GetString("page.bookmarks.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To allow the app to broadcast your location even when the app is minimized or the device screen is off, the app needs your permission.
        ///
        ///Please select &quot;Allow all the time&quot; for location permission in the next window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_location_permission_always {
            get {
                return ResourceManager.GetString("page.location_permission.always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To display your location on the map, the app needs your permission.
        ///
        ///Please click &quot;Allow&quot; in the next window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_location_permission_app_in_use {
            get {
                return ResourceManager.GetString("page.location_permission.app_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;ll pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_location_permission_cancel_btn {
            get {
                return ResourceManager.GetString("page.location_permission.cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK, I&apos;m in! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_location_permission_ok_btn {
            get {
                return ResourceManager.GetString("page.location_permission.ok_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To ensure the proper functioning of the Roadnik app, it is necessary to disable battery optimization. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_main_battery_optimization_body {
            get {
                return ResourceManager.GetString("page.main.battery_optimization.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery optimization is enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_main_battery_optimization_title {
            get {
                return ResourceManager.GetString("page.main.battery_optimization.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_connection_settings {
            get {
                return ResourceManager.GetString("page.options.connection_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The track from the previous recording session will not be preserved when you begin a new session に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_delete_old_route_desc {
            get {
                return ResourceManager.GetString("page.options.delete_old_route.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purge old tracks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_delete_old_route_title {
            get {
                return ResourceManager.GetString("page.options.delete_old_route.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_distance {
            get {
                return ResourceManager.GetString("page.options.distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum distance between sending location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_distance_hint {
            get {
                return ResourceManager.GetString("page.options.distance.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid room ID!
        ///
        ///Please specify the room ID in the settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_error_incorrect_room_id {
            get {
                return ResourceManager.GetString("page.options_error.incorrect_room_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid server address!
        ///
        ///Please specify a valid address in the settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_error_incorrect_server_address {
            get {
                return ResourceManager.GetString("page.options_error.incorrect_server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_error_open_settings {
            get {
                return ResourceManager.GetString("page.options_error.open_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPS consumes the most energy but has the highest accuracy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_gps_tooltip {
            get {
                return ResourceManager.GetString("page.options.gps.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location providers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_location_providers {
            get {
                return ResourceManager.GetString("page.options.location_providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WiFi/Cellular consumes less energy but has an accuracy of about 20-300 meters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_network_tooltip {
            get {
                return ResourceManager.GetString("page.options.network.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notifications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_notifications {
            get {
                return ResourceManager.GetString("page.options.notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Someone has created a new point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_notifications_new_point_desc {
            get {
                return ResourceManager.GetString("page.options.notifications.new_point.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new point was placed on the map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_notifications_new_point_title {
            get {
                return ResourceManager.GetString("page.options.notifications.new_point.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Someone has started a new track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_notifications_new_track_desc {
            get {
                return ResourceManager.GetString("page.options.notifications.new_track.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new track was started に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_notifications_new_track_title {
            get {
                return ResourceManager.GetString("page.options.notifications.new_track.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passive mode uses data obtained from other applications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_passive_tooltip {
            get {
                return ResourceManager.GetString("page.options.passive.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please pay attention: low-power location providers have poor accuracy (100m - 10000m).
        ///If the actual location accuracy will be less than the value of the &apos;%min-location-accuracy%&apos; option, the location will not be shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_accuracy_warning {
            get {
                return ResourceManager.GetString("page.options.power_mode.accuracy_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accuracy warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_accuracy_warning_title {
            get {
                return ResourceManager.GetString("page.options.power_mode.accuracy_warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPS consumes the most energy but has the highest accuracy.
        ///WiFi consumes less energy but has an accuracy of about 100 meters. 
        ///Cellular consumes the least energy, with an accuracy of kilometers. 
        ///Passive mode uses data obtained from other applications. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_desc {
            get {
                return ResourceManager.GetString("page.options.power_mode.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_high_accuracy {
            get {
                return ResourceManager.GetString("page.options.power_mode.high_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cellular に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_low_accuracy {
            get {
                return ResourceManager.GetString("page.options.power_mode.low_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WiFi/Cellular に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_medium_accuracy {
            get {
                return ResourceManager.GetString("page.options.power_mode.medium_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_passive {
            get {
                return ResourceManager.GetString("page.options.power_mode.passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location provider に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_power_mode_title {
            get {
                return ResourceManager.GetString("page.options.power_mode.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_roomId {
            get {
                return ResourceManager.GetString("page.options.roomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location share condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_share_condition {
            get {
                return ResourceManager.GetString("page.options.share_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your location will be sent when the following combination of the above conditions is met に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_share_condition_hint {
            get {
                return ResourceManager.GetString("page.options.share_condition.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_time_interval {
            get {
                return ResourceManager.GetString("page.options.time_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum time interval between sending location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_time_interval_hint {
            get {
                return ResourceManager.GetString("page.options.time_interval.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracking settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_tracking {
            get {
                return ResourceManager.GetString("page.options.tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required location accuracy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_tracking_required_accuracy {
            get {
                return ResourceManager.GetString("page.options.tracking.required_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_username {
            get {
                return ResourceManager.GetString("page.options.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string shell_about {
            get {
                return ResourceManager.GetString("shell.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string shell_bookmarks {
            get {
                return ResourceManager.GetString("shell.bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string shell_map {
            get {
                return ResourceManager.GetString("shell.map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string shell_settings {
            get {
                return ResourceManager.GetString("shell.settings", resourceCulture);
            }
        }
    }
}
