//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadnik.MAUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roadnik.MAUI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Success rate: %success/%total
        ///Last location fix: %last-location-fix
        ///Last location fix accuracy: %last-location-fix-accuracym
        ///Last successful report:%last-successful-report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_body {
            get {
                return ResourceManager.GetString("notification.location_sharing.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   never に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_body_never {
            get {
                return ResourceManager.GetString("notification.location_sharing.body_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your location is being shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification_location_sharing_title {
            get {
                return ResourceManager.GetString("notification.location_sharing.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_about_updateAvailable {
            get {
                return ResourceManager.GetString("page.about.updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_about_updating {
            get {
                return ResourceManager.GetString("page.about.updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_delete {
            get {
                return ResourceManager.GetString("page.bookmarks.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pull left to delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_delete_hint {
            get {
                return ResourceManager.GetString("page.bookmarks.delete_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_room {
            get {
                return ResourceManager.GetString("page.bookmarks.room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_title {
            get {
                return ResourceManager.GetString("page.bookmarks.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_bookmarks_username {
            get {
                return ResourceManager.GetString("page.bookmarks.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_connectionSettings {
            get {
                return ResourceManager.GetString("page.options.connectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The track from the previous recording session will not be preserved when you begin a new session に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_delete_old_route {
            get {
                return ResourceManager.GetString("page.options.delete_old_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low power mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_low_power_mode {
            get {
                return ResourceManager.GetString("page.options.low_power_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please pay attention: low-power location providers have poor accuracy (10m - 1000m). If the location accuracy is less than the value of the &apos;Required location accuracy&apos; option, the location will not be recorded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_low_power_mode_accuracy_warning {
            get {
                return ResourceManager.GetString("page.options.low_power_mode.accuracy_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accuracy warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_low_power_mode_accuracy_warning_title {
            get {
                return ResourceManager.GetString("page.options.low_power_mode.accuracy_warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use only Wi-Fi, Bluetooth, and cellular network location providers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_low_power_mode_hint {
            get {
                return ResourceManager.GetString("page.options.low_power_mode_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_roomId {
            get {
                return ResourceManager.GetString("page.options.roomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_serverAddress {
            get {
                return ResourceManager.GetString("page.options.serverAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string page_options_username {
            get {
                return ResourceManager.GetString("page.options.username", resourceCulture);
            }
        }
    }
}
