name: build-docker

on:
  push:
    branches:
      - 'dev/**'

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Install Python3   
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Build Docker Images
      run: python build-server-docker.py --platform linux-amd64
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }} 
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
